services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-volume:/var/lib/postgresql/data


  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    deploy:
    command: "start-dev"
    restart: always
    environment:
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_DB: postgres
      KC_HOSTNAME_STRICT: false
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_METRICS_ENABLED: true
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes: 
      - ./keycloakspi/target/keycloakspi-1.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloakspi-1.0-SNAPSHOT.jar
      - ./themes:/opt/keycloak/themes
    ports:
      - 8080:8080 # HTTPS is granted by reverse proxy (nginx)


volumes:
  postgres-volume:
    driver: local


